import localFont from 'next/font/local';
import './globals.css';
import { Providers } from './provider';

const graphik = localFont({
  src: [
    {
      path: '../public/fonts/Graphik-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../public/fonts/Graphik-Medium.ttf',
      weight: '600',
      style: 'bold'
    }
  ],
  variable: '--font-graphik',
  display: 'swap'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${graphik.variable}`} suppressHydrationWarning>
      <body className="text-black bg-white dark:text-white dark:bg-[#111010]">
        <Providers>
          <div className="px-8 max-w-[1100px] mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
